### PR TITLE
Add support for Sutter Lambda 721

### PR DESCRIPTION
**Pull request by dscbiggs**
Add support for Sutter Lambda 721 multi-LED light source as a Shutter device.
Allows single LED mode (same as a filter wheel), and multi-LED mode allowing up to 7 LEDs activated.  Also provides individual power % level.

### CODE REVIEW

**Comment by marktsuchida** [comment]
Thanks!

Just one thing: are the `#ifdef`s for `DefineLambda721` needed for something? Unless there is a need for it, I'd like to remove them to keep the build simpler (in particular, the macOS/Linux builds won't get the 721 code without additional configuration now).

**Comment by dscbiggs** [comment]
The define isn't needed.  I was just keeping the code separate incase I broke something or wasn't to be included.
You can remove them, or I can update the pull request.  Thanks for reviewing!

**Comment by marktsuchida** [comment]
@dscbiggs Thanks, would be great if you could do it (also maybe remove commented code where unlikely to be needed), but I can also do it tomorrow.

**Comment by dscbiggs** [comment]
I removed the define and unnecessary comments.  Thanks.

**Pull request merged**
