### PR TITLE
ASIStage: refactor into classes for each device

### PR DESCRIPTION
**Pull request by bls337**
Improvements to the organization of the ASIStage device adapter.

### CODE REVIEW

**Comment by marktsuchida** [comment]
@bls337 Is it okay if I "squash and merge" this (so that the whole PR becomes a single commit in the history)?
I think this will make sense because your individual commits appear to be separated by files they touched rather than the code being moved, and are therefore only the last commit will actually build.

**Comment by bls337** [comment]
Yeah that works for me, thanks.

**Comment by bls337** [comment]
@marktsuchida tagging you so that you see me reply.

**Comment by marktsuchida** [comment]
Thanks.

**Pull request merged**
