### PR TITLE
DahengGalaxy: based on code from Daheng 

### PR DESCRIPTION
**Pull request by nicost**
(which was basedon the BaslerPylon adapter code).  
Daheng grants free re-distribtion of their SDK to support building this code.  Relevant files have been added to 3rdpartypublic.

### CODE REVIEW

**Comment by marktsuchida** [comment]
```text
DeviceAdapters\DahengGalaxy\ClassGalaxy.h(6,10): fatal error C1083: Cannot open include file: 'GalaxyException.h': No such file or directory
```

Could there be a missing file GalaxyException.h?

**Comment by marktsuchida** [comment]
https://github.com/micro-manager/micro-manager/pull/1916

**Comment by nicost** [comment]
Thanks!

**Comment by pchiang5** [comment]
Hi,

Thank you for including this adapter!

The camera worked fine using the Live acquisition. However, the Snap button is greyed out in 'Live' mode, and when I tried to click on the 'Snap' button in the main interface, the following error appeared:

> Error: Failed to snap image.
> Camera image buffer read failed. 


It works fine when I use the demo camera. How should I resolve this issue? Thanks.

**Comment by nicost** [comment]
Please see my response to #470.

**Pull request merged**
