### PR TITLE
Fix two typos

### PR DESCRIPTION
**Pull request by HazenBabcock**
This replaces `PrepareSequenceAcqusition` with `PrepareSequenceAcquisition` and `g_Keyword_Meatdata_Exposure` with `g_Keyword_Metadata_Exposure`. It touches a lot of files because the first typo is present in most of the camera device adapters.

### CODE REVIEW

**Comment by tlambert03** [comment]
Hey @HazenBabcock 👋, this is a duplicate of #453  ... see discussion there for hesitation on merge

**Comment by HazenBabcock** [comment]
Yes it is, apologies for that.. I should have checked the open pull requests first..

**Comment by marktsuchida** [comment]
No problem, we appreciate this!

I think the `Meatdata` will be better to fix by keeping the old name (deprecated) for now, so as not to break things that depend on MMCore (including pymmcore), which exposes it in its API.

**Comment by HazenBabcock** [comment]
I could make another pull request where `Meatdata_Exposure` and 'Metadata_Exposure` are both set? Then once `Meatdata_Exposure` is fixed in the dependencies it could be removed?

**Comment by marktsuchida** [comment]
@HazenBabcock Yes, that would be perfect.

**Comment by HazenBabcock** [comment]
Closed, see #503.

**Pull request closed without merging**
