### PR TITLE
Add hikrobot camera plugin

### PR DESCRIPTION
**Pull request by sherlock2088**
a plugin to support hikrobot industry cameras.

### CODE REVIEW

**Comment by sherlock2088** [comment]
This pull request adds a device adapter for hikrobot cameras.
I'm not sure this pull request is actually ready to go in. I'm opening this pull request now to get some feedback about what else should go into the device adapter and the ways that it does not correctly conform to the MM expected camera behavior.

**Comment by sherlock2088** [comment]
In order to support the adapter, you should download SDK from hikrobot website.https://www.hikrobotics.com/en/machinevision/service/download?module=0

**Comment by nicost** [comment]
What is the license for the Include and Libs directories in the SD?  Can we publicly re-distribute these files (in our 3rdpartypublic svn repository)?

**Comment by sherlock2088** [comment]
> What is the license for the Include and Libs directories in the SD? Can we publicly re-distribute these files (in our 3rdpartypublic svn repository)?

SDK is free , everyone can download  from the hikrobot official website, and use develop your program, you can re-distribute theses files.

**Comment by nicost** [comment]
Sorry this took so long!  DeviceAdapter should be in the next nightly build.  Could you please test and let us know of any problems?

**Comment by sherlock2088** [comment]
> Sorry this took so long! DeviceAdapter should be in the next nightly build. Could you please test and let us know of any problems?

OK, the DeviceAdapter has been tested in windows platform. 
test

**Comment by sherlock2088** [comment]
> Sorry this took so long! DeviceAdapter should be in the next nightly build. Could you please test and let us know of any problems?

OK, the DeviceAdapter has been tested in windows platform. 
load
test

**Comment by nicost** [comment]
Looks good!  Thanks!

**Comment by Silver6** [comment]
Hello, Sherlock2088. You made a good job. But I did not success. The compilation of my program failed, prompting some error reports, and I compiled it according to the official website's prompts to RELEASE, again without success.
How do you do it?  Thanks. @sherlock2088 

> OK, the DeviceAdapter has been tested in windows platform. load test

**Comment by sherlock2088** [comment]
> Hello, Sherlock2088. You made a good job. But I did not success. The compilation of my program failed, prompting some error reports, and I compiled it according to the official website's prompts to RELEASE, again without success. How do you do it? Thanks. @sherlock2088
> 
> > OK, the DeviceAdapter has been tested in windows platform. load test

can you give some hints  or  snap a picture?

**Pull request merged**
