### PR TITLE
Add ZWO Camera  adapter

### PR DESCRIPTION
**Pull request by ZWODevTeam**
Hello! We have written the MicroManager plug-in for ASI cameras and now want to open source it into your source code base on GitHub. We are having problems submitting code to "mmCoreAndDevices". Git is telling us that we don't have permission to commit code to the repository. Our account name is: ZWO Development Team, hope you can give us some help. Thank you very much!

### CODE REVIEW

**Comment by nicost** [comment]
Perfect!  I will look at this merge request in detail tomorrow.  Couple of quick questions / suggestions:

- Are any files needed (that are not included) to compile and link the code?
- The .sln file is not needed.  However, leave it there for now, so that I can use it to the micromanager.sln file (one directory up in the source code tree).

**Comment by marktsuchida** [comment]
In addition:
- We need a license for this code ([BSD](https://spdx.org/licenses/BSD-3-Clause.html) or [LGPL](https://spdx.org/licenses/LGPL-2.1-or-later.html) strongly suggested).
- We do not normally include Windows resources in our device adapters. If the included resource files are important for the functioning of the device adapter, please let us know.

**Comment by ZWODevTeam** [comment]
Thank you for your reply. We have added the 'BSD' license and added some .lib files. Do we need to make a new Pull request?

**Comment by marktsuchida** [comment]
Thanks, and no need to make an new pull request. I will review this shortly.

**Comment by marktsuchida** [comment]
@ZWODevTeam

- Currently, the name of this device adapter is `MM_ASICam2`. It does not make sense to repeat "MM" in the name of a device adapter, so I'd like to rename it. But calling it `ASICam2` would probably be confusing, because we have existing device adapters (`ASIStage` and others) for the unrelated [ASI](https://www.asiimaging.com/) (a company well known to many MM users). Would you be okay with the name `ZWO_ASICam2`? Or perhaps just `ZWO`, given that this supports not just your camera but also filter wheel?

- I would like to remove the `.lib` files and place them in our internal storage for build dependencies. It is important to keep large binary files out of the Git repository, and also best to keep non-open-source files separate. Usually I do this by downloading the device SDK so that we know which version is in use, and also so that other people can build from publicly available files. But it looks like you included here static libraries that are different from the DLL+import libs in your SDKs (ASI_Windows_SDK_V1.28 and EFW_Windows_SDK_V1.7). Is it okay to use the SDK files to build?

**Comment by ZWODevTeam** [comment]
Thank you for your reply. We have changed to using the SDK's dynamic link library files

**Comment by marktsuchida** [comment]
Thanks. It looks like something caused a duplicate of MMDevice to get included in your commits, but I'll fix as necessary before merging (please give me 1-2 days).

Do you have a preferred name for the device adapter -- `ZWO` or `ZWO_ASICam2`? (See my previous comment.) This is the name that shows up in the Hardware Configuration Wizard. If you are okay with one of those names, I can change it for you -- no need for you to add commits for this.

**Comment by ZWODevTeam** [comment]
Thank you for helping us adjust the code.
Name for the device adapter could be changed to ZWO. Thanks.

**Comment by marktsuchida** [comment]
I'm going to rewrite the history in your branch (by force-pushing) to make the following changes:
- Remove all SDK files as well as other unnecessary files
- Rename the directory and project to `ZWO`
- Move the `license` file to `DeviceAdapters/ZWO/license.txt`
- Replace the Visual Studio project with one for VS2019 and correct settings
- Use SDK headers and libraries from our standard location (outside of the source tree)
- Make minor changes to the source code (usage of `MMTime`) so that it compiles with the current MMDevice
- Add the project to `micromanager.sln`

**Comment by marktsuchida** [comment]
@ZWODevTeam Please see #336 for the code that was actually merged.

**Pull request closed without merging**
