### PR TITLE
XLight V3 new Device Adapter

### PR DESCRIPTION
**Pull request by thefonzy0**

### CODE REVIEW

**Comment by marktsuchida** [comment]
Thank you for contributing this. Would you mind making the following changes so that it is consistent with the rest of our source tree?

- Please move the `.vcxproj` and `.vcxproj.filters` files to the same directory level (`DeviceAdapters/XLight_v3`).
- Please remove the `.sln` file (we'll add this project to the main `micromanager.sln` after merging).
- The name of the device adapter (that shows up in the Hardware Configuration Wizard) will be taken from the filename of the project. Do you intend this to be `XLight_V3.2`? If not, it will need to be renamed (e.g. to `XLightV3`). Also it would be good to match the directory name to the project name.
- The project file seems to contain some custom settings and also uses the old Windows7.1SDK. We now build with Visual Studio 2019 (or 2019 Tools with VS2022). Can you create the project file using the [current recommendations](https://micro-manager.org/Visual_Studio_project_settings_for_device_adapters)?

Let me know if you need any help with the details. Thanks.

**Comment by thefonzy0** [comment]
Hi Mark,
I proceeded to migrate to VS2019, but due to a high workload I never had time to complete the project check, in accordance with the requirements you indicated.. Today I have finally completed everything for update changes: I am new to using github and i hope i did everything right.

**Comment by marktsuchida** [comment]
@thefonzy0 Thanks. It looks like you merged `main` into your branch, but that doesn't change what is in this pull request (see the "Files changed" tab). Can you commit your new changes (if you haven't yet) and push that commit to this branch (`V3Branch`)? I might be able to help a little more if you can explain your current branch and commit situation.

Alternatively, I can fix the VS2019 settings and file locations for you. In this case, can you comment on the name to use for the device adapter (`XLight_V3.2` or `XLightV3` or other)?

**Comment by thefonzy0** [comment]
I believe I have succeeded.
I had tried this before with Git Gui (!), without success, while with git Bash it seems to have worked fine.
Thanks Mark.

**Comment by marktsuchida** [comment]
@thefonzy0 Thanks! I'll do a squash-and-merge to keep the history simple (free of unnecessary merges). Afterwards I'll use a separate pull request to add this to the main build files.

**Pull request merged**
