### PR TITLE
support new camera

### PR DESCRIPTION
**Pull request by fandayu**
support aries 16 lt/fl 9bw/fl 26bw

### CODE REVIEW

**Comment by fandayu** [comment]
support aries 16 lt/fl 9bw/fl 26bw

**Comment by marktsuchida** [comment]
@fandayu I merged this, but it does not compile, so I reverted the changes for now (#430). Happy to reapply the changes once fixed (probably easiest if you create a new pull request).

Do we perhaps need a newer SDK than the one available from the [download page](https://www.tucsen.com/download-software/page/2/)? We were using 20220808 and I also tried the latest.

Here are the errors (after upgrading to TUCam SDK V2.0.7.0_202305312):

```text
DeviceAdapters\TUCam\MMTUCam.cpp(472,16): error C2065: 'TUIDI_ZEROTEMPERATURE_VALUE': undeclared identifier
DeviceAdapters\TUCam\MMTUCam.cpp(632,20): error C2065: 'TUIDP_PIXELRATIO': undeclared identifier
DeviceAdapters\TUCam\MMTUCam.cpp(1316,22): error C2065: 'TUIDC_SIGNALFILTER': undeclared identifier
DeviceAdapters\TUCam\MMTUCam.cpp(3496,42): error C2065: 'TUIDP_PIXELRATIO': undeclared identifier
DeviceAdapters\TUCam\MMTUCam.cpp(3505,42): error C2065: 'TUIDP_PIXELRATIO': undeclared identifier
DeviceAdapters\TUCam\MMTUCam.cpp(6360,27): error C2065: 'TUCCM_TRIGGER_STANDARD_NONOVERLAP': undeclared identifier
DeviceAdapters\TUCam\MMTUCam.cpp(6419,13): error C2065: 'TUCCM_TRIGGER_STANDARD_NONOVERLAP': undeclared identifier
DeviceAdapters\TUCam\MMTUCam.cpp(6626,42): error C2065: 'TUIDC_SIGNALFILTER': undeclared identifier
DeviceAdapters\TUCam\MMTUCam.cpp(6634,42): error C2065: 'TUIDC_SIGNALFILTER': undeclared identifier
```

**Comment by fandayu** [comment]
Please update the new sdk header (TUCamApi.h and TUDefine.h) and library, I mail you, thks

**Comment by fandayu** [comment]
Hi Mark
Please update the attached file(TUCamApi.h and TUDefine.h).
ths


Dayu Fan  software engineer  
***@***.***     
            
Tel：0591-28055080        
Web：www.tucsen.com   
Tucsen Photonics Co., Ltd.
 
From: Mark Tsuchida
Date: 2024-01-12 08:10
To: micro-manager/mmCoreAndDevices
CC: fandayu; Mention
Subject: Re: [micro-manager/mmCoreAndDevices] support new camera (PR #429)
@fandayu I merged this, but it does not compile, so I reverted the changes for now (#430). Happy to reapply the changes once fixed (probably easiest if you create a new pull request).
Do we perhaps need a newer SDK than the one available from the download page? We were using 20220808 and I also tried the latest.
Here are the errors (after upgrading to TUCam SDK V2.0.7.0_202305312):
DeviceAdapters\TUCam\MMTUCam.cpp(472,16): error C2065: 'TUIDI_ZEROTEMPERATURE_VALUE': undeclared identifier
DeviceAdapters\TUCam\MMTUCam.cpp(632,20): error C2065: 'TUIDP_PIXELRATIO': undeclared identifier
DeviceAdapters\TUCam\MMTUCam.cpp(1316,22): error C2065: 'TUIDC_SIGNALFILTER': undeclared identifier
DeviceAdapters\TUCam\MMTUCam.cpp(3496,42): error C2065: 'TUIDP_PIXELRATIO': undeclared identifier
DeviceAdapters\TUCam\MMTUCam.cpp(3505,42): error C2065: 'TUIDP_PIXELRATIO': undeclared identifier
DeviceAdapters\TUCam\MMTUCam.cpp(6360,27): error C2065: 'TUCCM_TRIGGER_STANDARD_NONOVERLAP': undeclared identifier
DeviceAdapters\TUCam\MMTUCam.cpp(6419,13): error C2065: 'TUCCM_TRIGGER_STANDARD_NONOVERLAP': undeclared identifier
DeviceAdapters\TUCam\MMTUCam.cpp(6626,42): error C2065: 'TUIDC_SIGNALFILTER': undeclared identifier
DeviceAdapters\TUCam\MMTUCam.cpp(6634,42): error C2065: 'TUIDC_SIGNALFILTER': undeclared identifier

**Comment by fandayu** [comment]
Hi Mark
Add library file
Thks


Dayu Fan  software engineer  
***@***.***     
            
Tel：0591-28055080        
Web：www.tucsen.com   
Tucsen Photonics Co., Ltd.
 
From: ***@***.***
Date: 2024-01-12 10:29
To: micro-manager/mmCoreAndDevices; micro-manager/mmCoreAndDevices
CC: Mention
Subject: Re: Re: [micro-manager/mmCoreAndDevices] support new camera (PR #429)
Hi Mark
Please update the attached file(TUCamApi.h and TUDefine.h).
ths


Dayu Fan  software engineer  
***@***.***     
            
Tel：0591-28055080        
Web：www.tucsen.com   
Tucsen Photonics Co., Ltd.
 
From: Mark Tsuchida
Date: 2024-01-12 08:10
To: micro-manager/mmCoreAndDevices
CC: fandayu; Mention
Subject: Re: [micro-manager/mmCoreAndDevices] support new camera (PR #429)
@fandayu I merged this, but it does not compile, so I reverted the changes for now (#430). Happy to reapply the changes once fixed (probably easiest if you create a new pull request).
Do we perhaps need a newer SDK than the one available from the download page? We were using 20220808 and I also tried the latest.
Here are the errors (after upgrading to TUCam SDK V2.0.7.0_202305312):
DeviceAdapters\TUCam\MMTUCam.cpp(472,16): error C2065: 'TUIDI_ZEROTEMPERATURE_VALUE': undeclared identifier
DeviceAdapters\TUCam\MMTUCam.cpp(632,20): error C2065: 'TUIDP_PIXELRATIO': undeclared identifier
DeviceAdapters\TUCam\MMTUCam.cpp(1316,22): error C2065: 'TUIDC_SIGNALFILTER': undeclared identifier
DeviceAdapters\TUCam\MMTUCam.cpp(3496,42): error C2065: 'TUIDP_PIXELRATIO': undeclared identifier
DeviceAdapters\TUCam\MMTUCam.cpp(3505,42): error C2065: 'TUIDP_PIXELRATIO': undeclared identifier
DeviceAdapters\TUCam\MMTUCam.cpp(6360,27): error C2065: 'TUCCM_TRIGGER_STANDARD_NONOVERLAP': undeclared identifier
DeviceAdapters\TUCam\MMTUCam.cpp(6419,13): error C2065: 'TUCCM_TRIGGER_STANDARD_NONOVERLAP': undeclared identifier
DeviceAdapters\TUCam\MMTUCam.cpp(6626,42): error C2065: 'TUIDC_SIGNALFILTER': undeclared identifier
DeviceAdapters\TUCam\MMTUCam.cpp(6634,42): error C2065: 'TUIDC_SIGNALFILTER': undeclared identifier

**Comment by marktsuchida** [comment]
Thanks, I will do this.

**Comment by fandayu** [comment]
Hi Mark 
Please update file
[Tucsen_SDK_20240112.zip](https://github.com/micro-manager/mmCoreAndDevices/files/13926452/Tucsen_SDK_20240112.zip)

**Comment by fandayu** [comment]
Add new sdk's library
[Tucsen_SDK_20240112_1.zip](https://github.com/micro-manager/mmCoreAndDevices/files/13926459/Tucsen_SDK_20240112_1.zip)

**Comment by marktsuchida** [comment]
@fandayu Thank you, the changes have now been merged again in #432, using the 20240112 SDK.

**Pull request merged**
