### PR TITLE
Added device adapter for the ELL14

### PR DESCRIPTION
**Pull request by ManonPllat**
Add new Device Adapter for the Throlabs' ELL14.

### CODE REVIEW

**Comment by marktsuchida** [comment]
Sorry for the lack of reply. I'll definitely get to this this week.

**Comment by marktsuchida** [comment]
Thank you for contributing and apologies for taking so long to merge this!

**Comment by marktsuchida** [comment]
@ManonPllat I realized that there is no license attached to this. Can you create a separate pull request to add a license.txt file?

**Comment by ManonPllat** [comment]
Ok, I will do this as soon as the license is ready.

**Pull request merged**
