### PR TITLE
Adding the Pixelink Micromanager Device Adapter

### PR DESCRIPTION
**Pull request by pixelink-support**
Adding the Pixelink Micromanager Device Adapter to micromanager. This allows Micromanager users to operate Pixelink PL-D and PL-X cameras.

### CODE REVIEW

**Comment by marktsuchida** [comment]
Thank you for this. Can you please
- Add the `Pixelink.vcxproj.filters` file if you have it (unlike the `.user` file, the `.filters` file should be tracked in Git).
- Add a `license.txt` file or header comments that indicate the license (usually BSD or LGPL) under which you are making this code available.

Also, are there any build requirements (SDK?)

**Comment by pixelink-support** [comment]
Hello,

I have added the Pixelink.vcxproj.filters file a license file and a README file.

Building the Pixelink device adapter requires the use of the Pixelink SDK. I have included a reference to this fact in the README file

**Comment by marktsuchida** [comment]
@pixelink-support Thank you, I will review and merge this soon.

**Comment by marktsuchida** [comment]
@pixelink-support According to your [website](https://pixelink.com/products/software/sdk/) we need a license key to use your SDK. Will you be able to provide us with this? We would need this in order to build and include this in the Micro-Manager installer.

You can find my wisc.edu email in the Git commit log (`git log`) of this repository (or just google).

**Comment by marktsuchida** [comment]
I am going to merge this and follow it up with a separate pull request to fix project settings and add it to the build.

**Pull request merged**
