### PR TITLE
Fix pymmcore error messages

### PR DESCRIPTION
**Pull request by marktsuchida**
Transplanted from micro-manager/micro-manager#1157 by @tlambert03.

I will merge this shortly after a final review of exception types.

### CODE REVIEW

**Comment by marktsuchida** [comment]
I made some changes to the exception types, to better match Python's official definitions and actual usage of the errors in MMCore.

**Comment by tlambert03** [comment]
thanks!

**Comment by marktsuchida** [comment]
@tlambert03 You're welcome. Sorry this took so long.

**Comment by tlambert03** [comment]
no worries!

**Pull request merged**
