### PR TITLE
FRE / excelitas pco gmbh / 26.06.2024 / added 48bit RGB

### PR DESCRIPTION
**Pull request by franz-xaver**
Changed MicroManager.cpp in pco_generic device adapter.

FRE

### CODE REVIEW

**Comment by franz-xaver** [comment]
FRE

**Comment by marktsuchida** [comment]
@franz-xaver Thanks for the update.

I don't think we have standardized or documented how 16-bit-per-component RGB is supposed to work, and there are existing camera adapters that use an 8-byte (rather than 6-byte) format. Please give me a bit of time to review the situation to make sure that merging this will not produce compatibility problems in the future.

(I do hope that we can safely allow 48-bit RGB, just want to be sure.)

By the way, did you test this using MMStudio or some other way that goes through MMCore? If so, let me know how so that I can make sure to take that usage into consideration.

Also, does the buffer that you pass to `InsertImage()` contain the pixel components in R-G-B order (as opposed to B-G-R order)?

**Comment by franz-xaver** [comment]
@marktsuchida ...sorry for the last commit.

The title of the commit is not well verbalized. It is more a preparation for future things to come.

A customer asked me to add this image type into MM, but I did without success.

The code is just added but not active, as I could not add a 16bit RGB image:

```  if (m_pCamera->GetCCDCol(0))
  {
    pixTypes.push_back(g_PixelType_RGB32bit);
    //pixTypes.push_back(g_PixelType_RGB48bit); // Not possible up to now 07/22
    // Also GetImage does not convert to 48bit rgb, just 32bit rgb
  }```

Actually this is untested and RGB is not the order. It is just a naming. RGB vs. BGR should be added.

**Comment by franz-xaver** [comment]
Yes, correct.

**Pull request merged**
