### PR TITLE
Adding a new adapter UniversalMMHubUsb

### PR DESCRIPTION
**Pull request by artmeln**
There are two changes here:
1. My previously contributed UniversalSerialHub adapter has been renamed UniversalMMHubSerial for consistency.
2. A new adapter UniversalMMHubUsb has been added. This adapter relies on the libusb library, so I added a hard-coded path  to the Visual Studio project settings for now (my local /projects/3rdpartypublic/libusb-1.0.26). It seems that adding this dependency should be possible (https://github.com/micro-manager/mmCoreAndDevices/issues/186), and this adapter requires libusb to achieve high-speed bulk USB transfer

### CODE REVIEW

**Comment by artmeln** [comment]
I've updated both directories with the license files. Thanks for the suggestions, there is lot of code duplication between the USB and serial versions. I'll look into reorganizing based on the examples you mentioned.

**Comment by marktsuchida** [comment]
Thanks. I'll merge this once I've had a chance to add libusb-1.0. (You can do any reorganization later; I won't block this PR for that.)

**Comment by marktsuchida** [comment]
@artmeln Thanks for your patience. Would be great if you could check the nightly build (20220603 or later) to make sure it works. I used the static library from the official Windows binary package.

**Comment by artmeln** [comment]
I've verified that everything works as expected with the latest build. Thank you for your help.

**Pull request merged**
